[package]
name = "client"
version = "0.1.0"
edition = "2021"
authors = ["Mason Austin Green <mason@greenm01.net>"]

[profile.release]
opt-level = 'z'
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
