[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Mason Austin Green <mason@greenm01.net>"]

[profile.release]
opt-level = 'z'
lto = true

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
